# Generated by Django 5.1.3 on 2024-12-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_autor_emprestimos_remove_servico_cliente_editoras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='emprestimos',
            field=models.ManyToManyField(blank=True, null=True, to='backend.emprestimos'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='reservas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.reservas'),
        ),
    ]
