# Generated by Django 5.1.3 on 2024-12-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_livros_emprestimos_alter_livros_reservas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='emprestimos',
            field=models.ManyToManyField(blank=True, to='backend.emprestimos'),
        ),
    ]
