# Generated by Django 5.1.4 on 2024-12-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_usuarios_emprestimo_usuarios_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='emprestimo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='reserva',
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_usuario', to='backend.usuarios'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_usuario', to='backend.usuarios'),
        ),
    ]
