# Generated by Django 5.1.3 on 2024-12-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_livros_emprestimos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='reservas',
            field=models.ManyToManyField(blank=True, to='backend.reservas'),
        ),
    ]
