# Generated by Django 5.1.4 on 2024-12-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_autor_livros_alter_livros_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='livros',
            field=models.ManyToManyField(related_name='autores_livro', to='backend.livros'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores_livro', to='backend.autor'),
        ),
    ]
