# Generated by Django 5.1.4 on 2024-12-04 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_autor_livros_alter_livros_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='editora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='editora_autor', to='backend.editoras'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editoras',
            name='livros',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='editora_livro', to='backend.livros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='editora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editora_livro', to='backend.editoras'),
        ),
        migrations.AddField(
            model_name='livros',
            name='emprestimos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_livro', to='backend.emprestimos'),
        ),
        migrations.AddField(
            model_name='livros',
            name='reservas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_livro', to='backend.reservas'),
        ),
        migrations.RemoveField(
            model_name='editoras',
            name='autores',
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_livro', to='backend.livros'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_livro', to='backend.livros'),
        ),
        migrations.AddField(
            model_name='editoras',
            name='autores',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='editora_autor', to='backend.autor'),
            preserve_default=False,
        ),
    ]
