# Generated by Django 5.1.4 on 2024-12-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_autor_editora_editoras_livros_livros_editora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='author',
            new_name='autores',
        ),
    ]
