# Generated by Django 5.1.4 on 2024-12-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_author_livros_autores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='autores',
        ),
        migrations.AddField(
            model_name='livros',
            name='autores',
            field=models.ManyToManyField(related_name='autores_livro', to='backend.autor'),
        ),
    ]
