# Generated by Django 5.1.4 on 2024-12-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_usuarios_emprestimos_usuarios_reservas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='emprestimos',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='reservas',
        ),
    ]
